version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: bookstore-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres # Using postgres as default to allow init script to run
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init script
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Node.js application
  app:
    build: .
    container_name: bookstore-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: bookstore
      JWT_SECRET: bookstore_secret_key_for_development
      JWT_EXPIRES_IN: 1d
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      sh -c "npm install -g sequelize-cli &&
             npx sequelize-cli db:migrate &&
             if [ "$NODE_ENV" = "development" ]; then
               npx sequelize-cli db:seed:all
             fi &&
             npm start"

volumes:
  postgres-data:
